name: ci-workflow
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build & run tests
    # This job runs on Linux
    runs-on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v2
        - run: npm install webdriverio
        - run: ./node_modules/.bin/wdio wdio.conf.js